version: '3.9'

services:
  expense-tracker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  playwright-tests:
    build:
      context: .
      dockerfile: docker/Dockerfile.ui
    depends_on:
      expense-tracker:
        condition: service_healthy
    environment:
      - BASE_URL=http://expense-tracker:3000
      - RP_ENDPOINT=http://host.docker.internal:8080/api/v2
      - RP_API_KEY=robot-dreams_MUY79I08Rm-eHIiOFmvxP8S2dfscP1U1yKhB3AHs6aXwRcDMYrAp54oIiHsHDMol
      - RP_PROJECT=playwright-docker-reportportal
      - RP_LAUNCH=Playwright docker run
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
    # command: >
    #   bash -c "
    #     npx playwright test --reporter=html,allure-playwright &&
    #     npx allure generate --single-file allure-results --clean -o allure-report
    #   "

  playwright-report:
    image: nginx:alpine
    depends_on:
      - playwright-tests
    volumes:
      - ./playwright-report:/usr/share/nginx/html
    ports:
      - "8082:80"

  allure-report:
    image: nginx:alpine
    depends_on:
      - playwright-tests
    volumes:
      - ./allure-report:/usr/share/nginx/html
    ports:
      - "8083:80"

#  -d означає detached mode — тобто запуск у фоні.
# Run: docker-compose up --build -d
# To watch logs: docker-compose logs -f
# To stop: docker-compose down

# restart compose commands:
# docker-compose down
# docker-compose up --build -d
# docker-compose logs -f playwright-tests